[lightning]
region-concurrency = 24
status-addr = ':8289'
server-mode = false
level = "info"
file = "tidb-lightning.log"
check-requirements = false

[checkpoint]
enable=false

[tikv-importer]
backend = "local"
duplicate-resolution = 'none'
sorted-kv-dir = "/csv-data1/sorted-kv-dir"

[mydumper]
data-source-dir = "/csv-data1/csv-batch"
no-schema = true

[mydumper.csv]
separator = "\u0006"
delimiter = ''
terminator = "\u0007"
header = false
not-null = false
null = '\N'
backslash-escape = true
trim-last-separator = false

[tidb]
host = "10.200.40.41"
port = 4000
user = "root"
password = "JmuLrhyZx9pi"
status-port = 10080
pd-addr = "10.200.40.41:2379"

build-stats-concurrency = 20
distsql-scan-concurrency = 100
index-serial-scan-concurrency = 20
checksum-table-concurrency = 16

[post-restore]
checksum = "required"
analyze = "off"